# Generated by Django 5.2.1 on 2025-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="ride_score",
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="total_saved_money",
            field=models.IntegerField(default=0),
        ),
    ]
