# Generated by Django 5.2.1 on 2025-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notice_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridelog",
            name="provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
