# Generated by Django 5.2.1 on 2025-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_ridelog_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="total_distance_km",
            field=models.FloatField(default=0.0),
        ),
    ]
