# Generated by Django 5.2.1 on 2025-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userdata_total_distance_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridelog",
            name="saved_money",
            field=models.IntegerField(default=0),
        ),
    ]
